name: Dev Workflow

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.1'
          cache: 'yarn'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --prefer-offline
      - name: Test Lint
        run: yarn check-lint
      - name: Test Types
        run: yarn check-types
      - name: Run Tests
        run: yarn jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        name: Report Coverage to Pull Request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
          package-manager: yarn
          annotations: none
