name: Homolog Android Distribution
on:
  push:
    branches:
      - '**-hml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.1'
          cache: 'yarn'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_ENVIRONMENT: HOMOLOG
          file_name: .env
      - name: Prepare Secure Build
        run: bash secure-build-creator.sh -platform android -ANDROID_KEYSTORE '${{ secrets.ANDROID_KEYSTORE }}' -GSjson '${{ secrets.HML_GOOGLE_SERVICES_JSON }}' -ENV homolog
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --prefer-offline
      - name: Jetifier
        run: npx jetifier
      - name: Build
        run: cd android && ./gradlew app:assembleRelease
      - name: Fetch Firebase Credential File
        uses: ./.github/actions/base64-to-file
        with:
          secret: ${{ secrets.HML_CREDENTIAL_FILE_CONTENT }}
          filename: credential_file.json
          destination-path: $GITHUB_WORKSPACE/Firebase-Distribution-Github-Action/
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3
        with:
          appId: ${{ secrets.HML_FIREBASE_APP_ID_ANDROID }}
          serviceCredentialsFileContent: Firebase-Distribution-Github-Action/credential_file.json
          groups: testraul
          file: android/app/build/outputs/apk/release/app-release.apk
